name: "my-shell"
services:
  ssh:
    build:
      context: app
      target: builder
    hostname: tnas
    environment:
      USER_NAME: "mwiget"
      SUDO_ACCESS: "true"
    privileged: true
    volumes:
    - /home/mwiget:/config
    ports:
    - 22:2222
    - 60000-60100:60000-60100/udp
    dns_search:
      - tail27f72.ts.net
    deploy:
      replicas: 1
